/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AppTeamIndexRouteImport } from './routes/app/team/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppStartupsNewRouteImport } from './routes/app/startups/new'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStartupsNewRoute = AppStartupsNewRouteImport.update({
  id: '/startups/new',
  path: '/startups/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/pricing': typeof PricingIndexRoute
  '/app/startups/new': typeof AppStartupsNewRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/team': typeof AppTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/pricing': typeof PricingIndexRoute
  '/app/startups/new': typeof AppStartupsNewRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/team': typeof AppTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/pricing/': typeof PricingIndexRoute
  '/app/startups/new': typeof AppStartupsNewRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/team/': typeof AppTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/invite/$token'
    | '/pricing'
    | '/app/startups/new'
    | '/app/dashboard'
    | '/app/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/invite/$token'
    | '/pricing'
    | '/app/startups/new'
    | '/app/dashboard'
    | '/app/team'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/invite/$token'
    | '/pricing/'
    | '/app/startups/new'
    | '/app/dashboard/'
    | '/app/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  PricingIndexRoute: typeof PricingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team/': {
      id: '/app/team/'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/startups/new': {
      id: '/app/startups/new'
      path: '/startups/new'
      fullPath: '/app/startups/new'
      preLoaderRoute: typeof AppStartupsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppStartupsNewRoute: typeof AppStartupsNewRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppStartupsNewRoute: AppStartupsNewRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  PricingIndexRoute: PricingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
