/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStartupsRouteRouteImport } from './routes/app/startups/route'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/app/notifications/index'
import { Route as AppExploreIndexRouteImport } from './routes/app/explore/index'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as ApiDodoWebhooksRouteImport } from './routes/api/dodo/webhooks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSettingsBillingIndexRouteImport } from './routes/app/settings/billing/index'
import { Route as AppExploreStartupsIndexRouteImport } from './routes/app/explore/startups/index'
import { Route as AppExploreSprintsIndexRouteImport } from './routes/app/explore/sprints/index'
import { Route as AppSettingsBillingProRouteImport } from './routes/app/settings/billing/pro'
import { Route as AppDashboardStartupNewIndexRouteImport } from './routes/app/dashboard/startup/new/index'
import { Route as AppDashboardStartupNewVerifypanRouteImport } from './routes/app/dashboard/startup/new/verifypan'
import { Route as AppDashboardStartupNewConfirmRouteImport } from './routes/app/dashboard/startup/new/confirm'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStartupsRouteRoute = AppStartupsRouteRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreIndexRoute = AppExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiDodoWebhooksRoute = ApiDodoWebhooksRouteImport.update({
  id: '/api/dodo/webhooks',
  path: '/api/dodo/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsBillingIndexRoute = AppSettingsBillingIndexRouteImport.update({
  id: '/settings/billing/',
  path: '/settings/billing/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreStartupsIndexRoute = AppExploreStartupsIndexRouteImport.update({
  id: '/explore/startups/',
  path: '/explore/startups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExploreSprintsIndexRoute = AppExploreSprintsIndexRouteImport.update({
  id: '/explore/sprints/',
  path: '/explore/sprints/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsBillingProRoute = AppSettingsBillingProRouteImport.update({
  id: '/settings/billing/pro',
  path: '/settings/billing/pro',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardStartupNewIndexRoute =
  AppDashboardStartupNewIndexRouteImport.update({
    id: '/dashboard/startup/new/',
    path: '/dashboard/startup/new/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardStartupNewVerifypanRoute =
  AppDashboardStartupNewVerifypanRouteImport.update({
    id: '/dashboard/startup/new/verifypan',
    path: '/dashboard/startup/new/verifypan',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDashboardStartupNewConfirmRoute =
  AppDashboardStartupNewConfirmRouteImport.update({
    id: '/dashboard/startup/new/confirm',
    path: '/dashboard/startup/new/confirm',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/startups': typeof AppStartupsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dodo/webhooks': typeof ApiDodoWebhooksRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/explore': typeof AppExploreIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/billing/pro': typeof AppSettingsBillingProRoute
  '/app/explore/sprints': typeof AppExploreSprintsIndexRoute
  '/app/explore/startups': typeof AppExploreStartupsIndexRoute
  '/app/settings/billing': typeof AppSettingsBillingIndexRoute
  '/app/dashboard/startup/new/confirm': typeof AppDashboardStartupNewConfirmRoute
  '/app/dashboard/startup/new/verifypan': typeof AppDashboardStartupNewVerifypanRoute
  '/app/dashboard/startup/new': typeof AppDashboardStartupNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/startups': typeof AppStartupsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dodo/webhooks': typeof ApiDodoWebhooksRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/explore': typeof AppExploreIndexRoute
  '/app/notifications': typeof AppNotificationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/billing/pro': typeof AppSettingsBillingProRoute
  '/app/explore/sprints': typeof AppExploreSprintsIndexRoute
  '/app/explore/startups': typeof AppExploreStartupsIndexRoute
  '/app/settings/billing': typeof AppSettingsBillingIndexRoute
  '/app/dashboard/startup/new/confirm': typeof AppDashboardStartupNewConfirmRoute
  '/app/dashboard/startup/new/verifypan': typeof AppDashboardStartupNewVerifypanRoute
  '/app/dashboard/startup/new': typeof AppDashboardStartupNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/startups': typeof AppStartupsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dodo/webhooks': typeof ApiDodoWebhooksRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/explore/': typeof AppExploreIndexRoute
  '/app/notifications/': typeof AppNotificationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/settings/billing/pro': typeof AppSettingsBillingProRoute
  '/app/explore/sprints/': typeof AppExploreSprintsIndexRoute
  '/app/explore/startups/': typeof AppExploreStartupsIndexRoute
  '/app/settings/billing/': typeof AppSettingsBillingIndexRoute
  '/app/dashboard/startup/new/confirm': typeof AppDashboardStartupNewConfirmRoute
  '/app/dashboard/startup/new/verifypan': typeof AppDashboardStartupNewVerifypanRoute
  '/app/dashboard/startup/new/': typeof AppDashboardStartupNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/startups'
    | '/api/auth/$'
    | '/api/dodo/webhooks'
    | '/app/settings/profile'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/notifications'
    | '/app/settings'
    | '/app/settings/billing/pro'
    | '/app/explore/sprints'
    | '/app/explore/startups'
    | '/app/settings/billing'
    | '/app/dashboard/startup/new/confirm'
    | '/app/dashboard/startup/new/verifypan'
    | '/app/dashboard/startup/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/startups'
    | '/api/auth/$'
    | '/api/dodo/webhooks'
    | '/app/settings/profile'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/notifications'
    | '/app/settings'
    | '/app/settings/billing/pro'
    | '/app/explore/sprints'
    | '/app/explore/startups'
    | '/app/settings/billing'
    | '/app/dashboard/startup/new/confirm'
    | '/app/dashboard/startup/new/verifypan'
    | '/app/dashboard/startup/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/startups'
    | '/api/auth/$'
    | '/api/dodo/webhooks'
    | '/app/settings/profile'
    | '/app/dashboard/'
    | '/app/explore/'
    | '/app/notifications/'
    | '/app/settings/'
    | '/app/settings/billing/pro'
    | '/app/explore/sprints/'
    | '/app/explore/startups/'
    | '/app/settings/billing/'
    | '/app/dashboard/startup/new/confirm'
    | '/app/dashboard/startup/new/verifypan'
    | '/app/dashboard/startup/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDodoWebhooksRoute: typeof ApiDodoWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/startups': {
      id: '/app/startups'
      path: '/startups'
      fullPath: '/app/startups'
      preLoaderRoute: typeof AppStartupsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications/': {
      id: '/app/notifications/'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/explore/': {
      id: '/app/explore/'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/dodo/webhooks': {
      id: '/api/dodo/webhooks'
      path: '/api/dodo/webhooks'
      fullPath: '/api/dodo/webhooks'
      preLoaderRoute: typeof ApiDodoWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/billing/': {
      id: '/app/settings/billing/'
      path: '/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/explore/startups/': {
      id: '/app/explore/startups/'
      path: '/explore/startups'
      fullPath: '/app/explore/startups'
      preLoaderRoute: typeof AppExploreStartupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/explore/sprints/': {
      id: '/app/explore/sprints/'
      path: '/explore/sprints'
      fullPath: '/app/explore/sprints'
      preLoaderRoute: typeof AppExploreSprintsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/billing/pro': {
      id: '/app/settings/billing/pro'
      path: '/settings/billing/pro'
      fullPath: '/app/settings/billing/pro'
      preLoaderRoute: typeof AppSettingsBillingProRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/startup/new/': {
      id: '/app/dashboard/startup/new/'
      path: '/dashboard/startup/new'
      fullPath: '/app/dashboard/startup/new'
      preLoaderRoute: typeof AppDashboardStartupNewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/startup/new/verifypan': {
      id: '/app/dashboard/startup/new/verifypan'
      path: '/dashboard/startup/new/verifypan'
      fullPath: '/app/dashboard/startup/new/verifypan'
      preLoaderRoute: typeof AppDashboardStartupNewVerifypanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard/startup/new/confirm': {
      id: '/app/dashboard/startup/new/confirm'
      path: '/dashboard/startup/new/confirm'
      fullPath: '/app/dashboard/startup/new/confirm'
      preLoaderRoute: typeof AppDashboardStartupNewConfirmRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppStartupsRouteRoute: typeof AppStartupsRouteRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppExploreIndexRoute: typeof AppExploreIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsBillingProRoute: typeof AppSettingsBillingProRoute
  AppExploreSprintsIndexRoute: typeof AppExploreSprintsIndexRoute
  AppExploreStartupsIndexRoute: typeof AppExploreStartupsIndexRoute
  AppSettingsBillingIndexRoute: typeof AppSettingsBillingIndexRoute
  AppDashboardStartupNewConfirmRoute: typeof AppDashboardStartupNewConfirmRoute
  AppDashboardStartupNewVerifypanRoute: typeof AppDashboardStartupNewVerifypanRoute
  AppDashboardStartupNewIndexRoute: typeof AppDashboardStartupNewIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppStartupsRouteRoute: AppStartupsRouteRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppExploreIndexRoute: AppExploreIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsBillingProRoute: AppSettingsBillingProRoute,
  AppExploreSprintsIndexRoute: AppExploreSprintsIndexRoute,
  AppExploreStartupsIndexRoute: AppExploreStartupsIndexRoute,
  AppSettingsBillingIndexRoute: AppSettingsBillingIndexRoute,
  AppDashboardStartupNewConfirmRoute: AppDashboardStartupNewConfirmRoute,
  AppDashboardStartupNewVerifypanRoute: AppDashboardStartupNewVerifypanRoute,
  AppDashboardStartupNewIndexRoute: AppDashboardStartupNewIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDodoWebhooksRoute: ApiDodoWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
